export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';

export const GET_REVIEW = 'GET_REVIEW';
export const GET_REVIEW_SUCCESS = 'GET_REVIEW_SUCCESS';
export const TYPE_LOADING_SUCCESS = 'TYPE_LOADING_SUCCESS';
export const TYPE_LOADING = 'TYPE_LOADING';
