export const UPDATE_TRIP_DATE = 'UPDATE_TRIP_DATE';
export const UPDATE_TRIP_DATE_SUCCESS = 'UPDATE_TRIP_DATE_SUCCESS';
export const UPDATE_TRIP_DATE_FAILURE = 'UPDATE_TRIP_DATE_FAILURE';

export const UPDATE_TRIP_LOCATION = 'UPDATE_TRIP_LOCATION';
export const UPDATE_TRIP_LOCATION_SUCCESS = 'UPDATE_TRIP_LOCATION_SUCCESS';
export const UPDATE_TRIP_LOCATION_FAILURE = 'UPDATE_TRIP_LOCATION_FAILURE';

export const CLEAR_TRIP = 'CLEAR_TRIP';

export const SAVE_TRIP = 'SAVE_TRIP';
export const SAVE_TRIP_SUCCESS = 'SAVE_TRIP_SUCCESS';
export const SAVE_TRIP_FAILURE = 'SAVE_TRIP_FAILURE';

export const VENUES_UPDATE_USER = 'VENUES_UPDATE_USER';
export const VENUES_UPDATE_USER_SUCCESS = 'VENUES_UPDATE_USER_SUCCESS';
