export const SAVE_VENUE = 'SAVE_VENUE';
export const SAVE_VENUE_SUCCESS = 'SAVE_VENUE_SUCCESS';
export const SAVE_VENUE_FAILURE = 'SAVE_VENUE_FAILURE';
export const REMOVE_VENUE = 'REMOVE_VENUE';
export const REMOVE_VENUE_SUCCESS = 'REMOVE_VENUE_SUCCESS';
export const REMOVE_VENUE_FAILURE = 'REMOVE_VENUE_FAILURE';
